namespace AuthLibrary.Foundation.Security.Impl
{
	/// <summary>
	/// User class - Named it as CustomUser just to avoid conflict with the autogenerated User class
	/// </summary>
	public class CustomUser
	{
		/// <summary>
		/// User Id
		/// </summary>
		public string Id { get; set; }

		/// <summary>
		/// User Name
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// Password
		/// </summary>
		public string Password { get; set; }

		/// <summary>
		/// PasswordHash
		/// </summary>
		public string PasswordHash { get; set; }

		/// <summary>
		/// GrantToken
		/// </summary>
		public string GrantToken { get; set; }

		/// <summary>
		/// CompanyOrContext
		/// </summary>
		public string CompanyOrContext { get; set; }
	}
}